title: simoncastillo.github.io
description: .
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"
