title: /simoncastillo.github.io
description: <i>[Mad Hatter] "Do you think I've gone round the bend?" <br>[Alice] "I'm afraid so. You're mad, bonkers, completely off your head. But I'll tell you a secret. All the best people are."</i> 
show_downloads: true
theme: jekyll-theme-minimal
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
    author_profile: true
   
flickr:
  screen_name: You
  api_key: 53e7f6434beebf661f5e866970c1bb66
  api_secret: c0f66a3c0ff48f5f
