title: /simoncastillo.github.io
description: <i>[Mad Hatter] “Do you think I've gone round the bend?” [Alice]”I'm afraid so. You're mad, bonkers, completely off your head. But I'll tell you a secret. All the best people are.”</i> 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"
